<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!--
  EB_IS_2009: Editorial boards of Information System journals (JCR 2009 edition)
  @version 31-MAY-2011
  @author Guillaume Cabanac (guillaume.cabanac@univ-tlse3.fr)
-->
<!DOCTYPE boards [
<!ELEMENT boards (journal)+>
<!ELEMENT journal (titleISI , titleDBLP , isbn , publisher , if5years , researcher+)>
<!ELEMENT titleISI (#PCDATA)>
<!ELEMENT titleDBLP (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT if5years (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT researcher (#PCDATA)>
<!ATTLIST researcher sex (m | f | n) #REQUIRED>
<!ATTLIST researcher country CDATA #REQUIRED>
<!ATTLIST researcher level CDATA #REQUIRED>
]    >
<boards>
  <journal>
    <titleISI>Mis Quart</titleISI>
    <titleDBLP>MIS Quarterly</titleDBLP>
    <isbn>0276-7783</isbn>
    <publisher>U. Minnesota</publisher>
    <if5years> 9.208</if5years>
    <researcher sex="m" country="us" level="3">Detmar W. Straub</researcher>
    <researcher sex="f" country="sg" level="2">Soon Ang</researcher>
    <researcher sex="m" country="us" level="2">Ravi Bapna</researcher>
    <researcher sex="m" country="ca" level="2">Henri Barki</researcher>
    <researcher sex="f" country="au" level="2">Shirley Gregor</researcher>
    <researcher sex="m" country="us" level="2">Vijay Gurbaxani</researcher>
    <researcher sex="m" country="se" level="2">Ola Henfridsson</researcher>
    <researcher sex="m" country="us" level="2">Alan R. Hevner</researcher>
    <researcher sex="m" country="fi" level="2">Juhani Iivari</researcher>
    <researcher sex="m" country="us" level="2">Rajiv Kohli</researcher>
    <researcher sex="m" country="hk" level="2">Kai H. Lim</researcher>
    <researcher sex="f" country="us" level="2">Ann Majchrzak</researcher>
    <researcher sex="m" country="us" level="2">Michael G. Morris</researcher>
    <researcher sex="f" country="ca" level="2">Suzanne Rivard</researcher>
    <researcher sex="m" country="us" level="2">Suprateek Sarker</researcher>
    <researcher sex="f" country="uk" level="2">Cathy Urquhart</researcher>
    <researcher sex="m" country="us" level="2">Vijay K. Vaishnavi</researcher>
    <researcher sex="m" country="us" level="2">Joseph S. Valacich</researcher>
    <researcher sex="f" country="us" level="2">Fatemeh Zahedi</researcher>
    <researcher sex="f" country="us" level="1">Manju K. Ahuja</researcher>
    <researcher sex="f" country="uk" level="1">Chrisanthi Avgerou</researcher>
    <researcher sex="f" country="us" level="1">Sulin Ba</researcher>
    <researcher sex="f" country="us" level="1">Marie-Claude Boudreau</researcher>
    <researcher sex="m" country="de" level="1">Sjaak Brinkkemper</researcher>
    <researcher sex="m" country="ca" level="1">Andrew Burton-Jones</researcher>
    <researcher sex="m" country="us" level="1">Samir Chatterjee</researcher>
    <researcher sex="m" country="hk" level="1">Patrick Y. K. Chau</researcher>
    <researcher sex="m" country="hk" level="1">Robert M. Davison</researcher>
    <researcher sex="m" country="ch" level="1">Jens Dibbern</researcher>
    <researcher sex="m" country="us" level="1">Thomas W. Ferratt</researcher>
    <researcher sex="m" country="us" level="1">David Gefen</researcher>
    <researcher sex="m" country="us" level="1">Peter H. Gray</researcher>
    <researcher sex="m" country="ca" level="1">Christopher A. Higgins</researcher>
    <researcher sex="m" country="nz" level="1">Sid L. Huff</researcher>
    <researcher sex="m" country="au" level="1">James J. Jiang</researcher>
    <researcher sex="m" country="ie" level="1">Robert B. Johnston</researcher>
    <researcher sex="f" country="sg" level="1">Atreyi Kankanhalli</researcher>
    <researcher sex="m" country="us" level="1">Gary Klein</researcher>
    <researcher sex="m" country="kr" level="1">Jae-Nam Lee</researcher>
    <researcher sex="m" country="se" level="1">Magnus Mähring</researcher>
    <researcher sex="m" country="us" level="1">Arvind Malhotra</researcher>
    <researcher sex="m" country="us" level="1">Likoebe M. Maruping</researcher>
    <researcher sex="m" country="us" level="1">D. Harrison McKnight</researcher>
    <researcher sex="m" country="uk" level="1">John Mingers</researcher>
    <researcher sex="m" country="sg" level="1">Shan Ling Pan</researcher>
    <researcher sex="f" country="us" level="1">Suzanne D. Pawlowski</researcher>
    <researcher sex="m" country="us" level="1">Sandeep Purao</researcher>
    <researcher sex="m" country="us" level="1">Ronald L. Thompson</researcher>
    <researcher sex="f" country="us" level="1">Eileen M. Trauth</researcher>
    <researcher sex="m" country="us" level="1">Tunay I. Tunca</researcher>
    <researcher sex="f" country="us" level="1">Emmanuelle Vaast</researcher>
    <researcher sex="m" country="us" level="1">Eric Walden</researcher>
    <researcher sex="f" country="us" level="1">Molly Wasko</researcher>
    <researcher sex="m" country="uk" level="1">Bruce W. Weber</researcher>
    <researcher sex="m" country="us" level="1">John D. Wells</researcher>
    <researcher sex="m" country="us" level="1">Youngjin Yoo</researcher>
  </journal>
  <journal>
    <titleISI>VLDB J</titleISI>
    <titleDBLP>VLDB J.</titleDBLP>
    <isbn>1066-8888</isbn>
    <publisher>Springer</publisher>
    <if5years> 6.987</if5years>
    <researcher sex="m" country="us" level="4">Philip A. Bernstein</researcher>
    <researcher sex="m" country="dk" level="4">Christian S. Jensen</researcher>
    <researcher sex="m" country="sg" level="4">Kian-Lee Tan</researcher>
    <researcher sex="m" country="de" level="3">Klemens Böhm</researcher>
    <researcher sex="m" country="sg" level="2">Christian von der Weth</researcher>
    <researcher sex="m" country="us" level="1">Amr El Abbadi</researcher>
    <researcher sex="f" country="ch" level="1">Anastasia Ailamaki</researcher>
    <researcher sex="f" country="us" level="1">Sihem Amer-Yahia</researcher>
    <researcher sex="m" country="it" level="1">Claudio Bettini</researcher>
    <researcher sex="m" country="ch" level="1">Michael H. Böhlen</researcher>
    <researcher sex="m" country="au" level="1">Athman Bouguettaya</researcher>
    <researcher sex="m" country="us" level="1">Peter Buneman</researcher>
    <researcher sex="m" country="us" level="1">K. Selçuk Candan</researcher>
    <researcher sex="f" country="it" level="1">Tiziana Catarci</researcher>
    <researcher sex="m" country="us" level="1">Ugur Çetintemel</researcher>
    <researcher sex="m" country="kr" level="1">Sang Kyun Cha</researcher>
    <researcher sex="m" country="us" level="1">Johannes Gehrke</researcher>
    <researcher sex="m" country="de" level="1">Michael Gertz</researcher>
    <researcher sex="m" country="us" level="1">Peter J. Haas</researcher>
    <researcher sex="m" country="in" level="1">Jayant R. Haritsa</researcher>
    <researcher sex="m" country="us" level="1">Chris Jermaine</researcher>
    <researcher sex="m" country="de" level="1">Alfons Kemper</researcher>
    <researcher sex="m" country="de" level="1">Hans-Peter Kriegel</researcher>
    <researcher sex="m" country="de" level="1">Wolfgang Lehner</researcher>
    <researcher sex="m" country="us" level="1">Ninghui Li</researcher>
    <researcher sex="m" country="us" level="1">Guy M. Lohman</researcher>
    <researcher sex="f" country="ca" level="1">Renée J. Miller</researcher>
    <researcher sex="f" country="il" level="1">Tova Milo</researcher>
    <researcher sex="m" country="hk" level="1">Dimitris Papadias</researcher>
    <researcher sex="m" country="uk" level="1">Norman W. Paton</researcher>
    <researcher sex="m" country="au" level="1">Kotagiri Ramamohanarao</researcher>
    <researcher sex="f" country="us" level="1">Elke A. Rundensteiner</researcher>
    <researcher sex="m" country="de" level="1">Thomas Seidl</researcher>
    <researcher sex="m" country="us" level="1">Cyrus Shahabi</researcher>
    <researcher sex="f" country="us" level="1">Bhavani M. Thuraisingham</researcher>
    <researcher sex="m" country="ca" level="1">David Toman</researcher>
    <researcher sex="f" country="us" level="1">Marianne Winslett</researcher>
    <researcher sex="m" country="jp" level="1">Haruo Yokota</researcher>
    <researcher sex="m" country="hk" level="1">Jeffrey Xu Yu</researcher>
    <researcher sex="m" country="us" level="1">Carlo Zaniolo</researcher>
    <researcher sex="m" country="au" level="1">Xiaofang Zhou</researcher>
    <researcher sex="m" country="cn" level="1">Aoying Zhou</researcher>
  </journal>
  <journal>
    <titleISI>ACM T Inform Syst</titleISI>
    <titleDBLP>ACM Trans. Inf. Syst.</titleDBLP>
    <isbn>1046-8188</isbn>
    <publisher>ACM</publisher>
    <if5years> 5.774</if5years>
    <researcher sex="m" country="us" level="2">James P. Callan</researcher>
    <researcher sex="m" country="cl" level="1">Ricardo A. Baeza-Yates</researcher>
    <researcher sex="m" country="us" level="1">Andrei Z. Broder</researcher>
    <researcher sex="m" country="sg" level="1">Tat-Seng Chua</researcher>
    <researcher sex="f" country="us" level="1">Susan T. Dumais</researcher>
    <researcher sex="m" country="us" level="1">Edward A. Fox</researcher>
    <researcher sex="m" country="de" level="1">Norbert Fuhr</researcher>
    <researcher sex="f" country="es" level="1">Mounia Lalmas</researcher>
    <researcher sex="f" country="us" level="1">Elizabeth D. Liddy</researcher>
    <researcher sex="m" country="sg" level="1">Ee-Peng Lim</researcher>
    <researcher sex="m" country="cn" level="1">Tie-Yan Liu</researcher>
    <researcher sex="m" country="cn" level="1">Wei-Ying Ma</researcher>
    <researcher sex="m" country="au" level="1">Alistair Moffat</researcher>
    <researcher sex="m" country="us" level="1">Douglas W. Oard</researcher>
    <researcher sex="f" country="us" level="1">Edie M. Rasmussen</researcher>
    <researcher sex="m" country="nl" level="1">Maarten de Rijke</researcher>
    <researcher sex="m" country="uk" level="1">Stefan M. Rüger</researcher>
    <researcher sex="m" country="au" level="1">Mark Sanderson</researcher>
    <researcher sex="m" country="it" level="1">Fabrizio Sebastiani</researcher>
    <researcher sex="m" country="us" level="1">Luo Si</researcher>
    <researcher sex="m" country="at" level="1">John Tait</researcher>
    <researcher sex="m" country="us" level="1">Ryen W. White</researcher>
    <researcher sex="m" country="us" level="1">ChengXiang Zhai</researcher>
    <researcher sex="f" country="us" level="1">Yi Zhang</researcher>
    <researcher sex="m" country="au" level="1">Justin Zobel</researcher>
  </journal>
  <journal>
    <titleISI>J Am Med Inform Assn</titleISI>
    <titleDBLP>JAMIA</titleDBLP>
    <isbn>1067-5027</isbn>
    <publisher>BMJ</publisher>
    <if5years> 5.199</if5years>
    <researcher sex="f" country="us" level="3">Lucila Ohno-Machado</researcher>
    <researcher sex="f" country="us" level="2">Patricia Flatley Brennan</researcher>
    <researcher sex="m" country="us" level="2">Atul J. Butte</researcher>
    <researcher sex="m" country="au" level="2">Enrico W. Coiera</researcher>
    <researcher sex="m" country="us" level="2">Charles P. Friedman</researcher>
    <researcher sex="f" country="us" level="2">Betsy L. Humphreys</researcher>
    <researcher sex="m" country="us" level="2">Kevin B. Johnson</researcher>
    <researcher sex="m" country="us" level="2">Harold P. Lehmann</researcher>
    <researcher sex="m" country="us" level="2">Prakash M. Nadkarni</researcher>
    <researcher sex="f" country="us" level="1">Patricia A. Abbott</researcher>
    <researcher sex="m" country="us" level="1">Michael J. Ackerman</researcher>
    <researcher sex="m" country="us" level="1">Russ B. Altman</researcher>
    <researcher sex="m" country="us" level="1">James G. Anderson</researcher>
    <researcher sex="m" country="ch" level="1">Dominik Aronsky</researcher>
    <researcher sex="f" country="us" level="1">Joan S. Ash</researcher>
    <researcher sex="f" country="us" level="1">Suzanne Bakken</researcher>
    <researcher sex="m" country="us" level="1">Douglas S. Bell</researcher>
    <researcher sex="f" country="us" level="1">Eta S. Berner</researcher>
    <researcher sex="m" country="us" level="1">Olivier Bodenreider</researcher>
    <researcher sex="f" country="us" level="1">Cynthia Brandt</researcher>
    <researcher sex="f" country="us" level="1">Wendy Webber Chapman</researcher>
    <researcher sex="m" country="us" level="1">Michael F. Chiang</researcher>
    <researcher sex="m" country="us" level="1">Christopher G. Chute</researcher>
    <researcher sex="m" country="us" level="1">Stephen M. Downs</researcher>
    <researcher sex="m" country="us" level="1">Peter J. Embi</researcher>
    <researcher sex="m" country="us" level="1">R. Scott Evans</researcher>
    <researcher sex="f" country="us" level="1">Carol Friedman</researcher>
    <researcher sex="m" country="us" level="1">Mark E. Frisse</researcher>
    <researcher sex="f" country="us" level="1">Susan J. Grobe</researcher>
    <researcher sex="m" country="us" level="1">John H. Holmes</researcher>
    <researcher sex="m" country="us" level="1">George Hripcsak</researcher>
    <researcher sex="m" country="us" level="1">Michael G. Kahn</researcher>
    <researcher sex="m" country="us" level="1">Michael Krauthammer</researcher>
    <researcher sex="f" country="us" level="1">Rita Kukafka</researcher>
    <researcher sex="m" country="us" level="1">Gilad J. Kuperman</researcher>
    <researcher sex="m" country="us" level="1">Leslie Lenert</researcher>
    <researcher sex="m" country="ch" level="1">Christian Lovis</researcher>
    <researcher sex="m" country="us" level="1">Henry J. Lowe</researcher>
    <researcher sex="m" country="us" level="1">Yves A. Lussier</researcher>
    <researcher sex="m" country="us" level="1">Kenneth D. Mandl</researcher>
    <researcher sex="f" country="us" level="1">Julie J. McGowan</researcher>
    <researcher sex="f" country="ca" level="1">K. Ann McKibbon</researcher>
    <researcher sex="m" country="us" level="1">Perry L. Miller</researcher>
    <researcher sex="f" country="us" level="1">Joyce C. Niland</researcher>
    <researcher sex="m" country="us" level="1">J. Marc Overhage</researcher>
    <researcher sex="m" country="us" level="1">Philip R. O. Payne</researcher>
    <researcher sex="m" country="us" level="1">Thomas H. Payne</researcher>
    <researcher sex="m" country="us" level="1">Eric G. Poon</researcher>
    <researcher sex="m" country="uk" level="1">Alan L. Rector</researcher>
    <researcher sex="f" country="us" level="1">Rachel L. Richesson</researcher>
    <researcher sex="m" country="us" level="1">S. Trent Rosenbloom</researcher>
    <researcher sex="m" country="us" level="1">Indra Neil Sarkar</researcher>
    <researcher sex="m" country="us" level="1">M. Michael Shabot</researcher>
    <researcher sex="m" country="us" level="1">Steven Shea</researcher>
    <researcher sex="f" country="us" level="1">Catherine J. Staes</researcher>
    <researcher sex="m" country="us" level="1">Jaap Suermondt</researcher>
    <researcher sex="m" country="us" level="1">Peter Tarczy-Hornoch</researcher>
    <researcher sex="m" country="us" level="1">Martin C. Were</researcher>
    <researcher sex="m" country="us" level="1">W. John Wilbur</researcher>
  </journal>
  <journal>
    <titleISI>IEEE Wirel Commun</titleISI>
    <titleDBLP>IEEE Transactions on Wireless Communications</titleDBLP>
    <isbn>1536-1284</isbn>
    <publisher>IEEE</publisher>
    <if5years> 4.534</if5years>
    <researcher sex="m" country="us" level="3">Larry J. Greenstein</researcher>
    <researcher sex="m" country="us" level="3">Leonard J. Cimini Jr.</researcher>
    <researcher sex="m" country="us" level="3">Chengshan Xiao</researcher>
    <researcher sex="m" country="us" level="2">Zhi Ding</researcher>
    <researcher sex="f" country="us" level="2">Andrea J. Goldsmith</researcher>
    <researcher sex="m" country="hk" level="2">Khaled Ben Letaief</researcher>
    <researcher sex="m" country="us" level="2">Theodore S. Rappaport</researcher>
    <researcher sex="m" country="fi" level="1">Giuseppe Thadeu Freitas de Abreu</researcher>
    <researcher sex="m" country="ca" level="1">Sofiène Affes</researcher>
    <researcher sex="f" country="ca" level="1">Sonia Aïssa</researcher>
    <researcher sex="m" country="ca" level="1">Masoud Ardakani</researcher>
    <researcher sex="m" country="in" level="1">Srikrishna Bhashyam</researcher>
    <researcher sex="m" country="ca" level="1">Steven D. Blostein</researcher>
    <researcher sex="m" country="us" level="1">R. Michael Buehrer</researcher>
    <researcher sex="m" country="in" level="1">Ananthanarayanan Chockalingam</researcher>
    <researcher sex="m" country="kr" level="1">Wan Choi</researcher>
    <researcher sex="f" country="us" level="1">Chia-Chin Chong</researcher>
    <researcher sex="m" country="it" level="1">Giulio Colavolpe</researcher>
    <researcher sex="m" country="uk" level="1">Justin P. Coon</researcher>
    <researcher sex="m" country="fi" level="1">Carlos de M. Cordeiro</researcher>
    <researcher sex="m" country="mx" level="1">Felipe A. Cruz-Pérez</researcher>
    <researcher sex="m" country="in" level="1">Onkar Dabeer</researcher>
    <researcher sex="m" country="it" level="1">Davide Dardari</researcher>
    <researcher sex="m" country="ca" level="1">Timothy N. Davidson</researcher>
    <researcher sex="f" country="ca" level="1">Xiaodai Dong</researcher>
    <researcher sex="m" country="us" level="1">Greg Durgin</researcher>
    <researcher sex="m" country="uk" level="1">Albert Guillen i Fabregas</researcher>
    <researcher sex="m" country="cn" level="1">Xiqi Gao</researcher>
    <researcher sex="m" country="fr" level="1">David Gesbert</researcher>
    <researcher sex="m" country="us" level="1">Saeed S. Ghassemzadeh</researcher>
    <researcher sex="m" country="ca" level="1">T. Aaron Gulliver</researcher>
    <researcher sex="m" country="us" level="1">Ibrahim Habib</researcher>
    <researcher sex="m" country="no" level="1">Are Hjørungnes</researcher>
    <researcher sex="m" country="kr" level="1">Daesik Hong</researcher>
    <researcher sex="m" country="ca" level="1">Ekram Hossain</researcher>
    <researcher sex="m" country="us" level="1">Yiwei Thomas Hou</researcher>
    <researcher sex="m" country="au" level="1">Defeng Huang</researcher>
    <researcher sex="m" country="us" level="1">Hamid Jafarkhani</researcher>
    <researcher sex="m" country="jp" level="1">Nei Kato</researcher>
    <researcher sex="m" country="kr" level="1">Dong In Kim</researcher>
    <researcher sex="m" country="kr" level="1">Kwang Soon Kim</researcher>
    <researcher sex="m" country="ca" level="1">Il-Min Kim</researcher>
    <researcher sex="m" country="ca" level="1">Lutz H.-J. Lampe</researcher>
    <researcher sex="m" country="hk" level="1">Vincent K. N. Lau</researcher>
    <researcher sex="m" country="kr" level="1">Kwang Bok Lee</researcher>
    <researcher sex="m" country="kr" level="1">Inkyu Lee</researcher>
    <researcher sex="m" country="us" level="1">Ye Li</researcher>
    <researcher sex="m" country="ca" level="1">Ben Liang</researcher>
    <researcher sex="f" country="tw" level="1">Wanjiun Liao</researcher>
    <researcher sex="f" country="us" level="1">Wenjing Lou</researcher>
    <researcher sex="f" country="us" level="1">Jun Lu</researcher>
    <researcher sex="f" country="us" level="1">Jianghong Luo</researcher>
    <researcher sex="f" country="us" level="1">Xiaoli Ma</researcher>
    <researcher sex="m" country="in" level="1">Ranjan K. Mallik</researcher>
    <researcher sex="m" country="us" level="1">Giridhar D. Mandyam</researcher>
    <researcher sex="m" country="in" level="1">Neelesh B. Mehta</researcher>
    <researcher sex="f" country="it" level="1">Maria Luisa Merani</researcher>
    <researcher sex="m" country="us" level="1">Andreas F. Molisch</researcher>
    <researcher sex="f" country="it" level="1">Michele Morelli</researcher>
    <researcher sex="m" country="hk" level="1">Ross D. Murch</researcher>
    <researcher sex="m" country="us" level="1">Rohit U. Nabar</researcher>
    <researcher sex="m" country="uk" level="1">Arumugam Nallanathan</researcher>
    <researcher sex="m" country="ca" level="1">Ha H. Nguyen</researcher>
    <researcher sex="m" country="us" level="1">Aria Nosratinia</researcher>
    <researcher sex="m" country="jp" level="1">Hideki Ochiai</researcher>
    <researcher sex="m" country="za" level="1">Jan C. Olivier</researcher>
    <researcher sex="m" country="gr" level="1">Constantinos B. Papadias</researcher>
    <researcher sex="f" country="gr" level="1">Fotini-Niovi Pavlidou</researcher>
    <researcher sex="m" country="in" level="1">B. Sundar Rajan</researcher>
    <researcher sex="m" country="ca" level="1">Mohammad Mamunur Rashid</researcher>
    <researcher sex="m" country="us" level="1">Daryl Reynolds</researcher>
    <researcher sex="m" country="gr" level="1">Nikos C. Sagias</researcher>
    <researcher sex="m" country="jp" level="1">Yukitoshi Sanada</researcher>
    <researcher sex="m" country="nz" level="1">Mansoor Shafi</researcher>
    <researcher sex="m" country="us" level="1">John M. Shea</researcher>
    <researcher sex="m" country="kr" level="1">Hyundong Shin</researcher>
    <researcher sex="m" country="us" level="1">Osvaldo Simeone</researcher>
    <researcher sex="m" country="za" level="1">Fambirai Takawira</researcher>
    <researcher sex="f" country="cn" level="1">Meixia Tao</researcher>
    <researcher sex="m" country="it" level="1">Daniele Tarchi</researcher>
    <researcher sex="m" country="ca" level="1">Chintha Tellambura</researcher>
    <researcher sex="m" country="us" level="1">Murat Torlak</researcher>
    <researcher sex="m" country="se" level="1">Fredrik Tufvesson</researcher>
    <researcher sex="m" country="us" level="1">Jitendra K. Tugnait</researcher>
    <researcher sex="m" country="ca" level="1">Murat Uysal</researcher>
    <researcher sex="m" country="us" level="1">Matthew C. Valenti</researcher>
    <researcher sex="m" country="it" level="1">Giorgio Matteo Vitetta</researcher>
    <researcher sex="m" country="us" level="1">Xiaodong Wang</researcher>
    <researcher sex="m" country="us" level="1">Shuangqing Wei</researcher>
    <researcher sex="m" country="us" level="1">Moe Z. Win</researcher>
    <researcher sex="m" country="uk" level="1">Kai-Kit Wong</researcher>
    <researcher sex="m" country="us" level="1">Xiang-Gen Xia</researcher>
    <researcher sex="m" country="us" level="1">Guoliang Xue</researcher>
    <researcher sex="m" country="cn" level="1">Lin Yang</researcher>
    <researcher sex="f" country="us" level="1">Aylin Yener</researcher>
    <researcher sex="m" country="fr" level="1">Djamal Zeghlache</researcher>
    <researcher sex="f" country="hk" level="1">Ying Jun Zhang</researcher>
    <researcher sex="m" country="hk" level="1">Keith Q. T. Zhang</researcher>
  </journal>
  <journal>
    <titleISI>Data Min Knowl Disc</titleISI>
    <titleDBLP>Data Min. Knowl. Discov.</titleDBLP>
    <isbn>1384-5810</isbn>
    <publisher>Springer</publisher>
    <if5years> 4.432</if5years>
    <researcher sex="m" country="au" level="4">Geoffrey I. Webb</researcher>
    <researcher sex="m" country="us" level="3">Usama M. Fayyad</researcher>
    <researcher sex="m" country="fi" level="3">Heikki Mannila</researcher>
    <researcher sex="m" country="us" level="3">Raghu Ramakrishnan</researcher>
    <researcher sex="m" country="us" level="2">Charu C. Aggarwal</researcher>
    <researcher sex="m" country="us" level="2">Pierre Baldi</researcher>
    <researcher sex="m" country="us" level="2">Roberto J. Bayardo</researcher>
    <researcher sex="f" country="us" level="2">Jennifer G. Dy</researcher>
    <researcher sex="f" country="us" level="2">Tina Eliassi-Rad</researcher>
    <researcher sex="m" country="us" level="2">Charles Elkan</researcher>
    <researcher sex="m" country="de" level="2">Johannes Fürnkranz</researcher>
    <researcher sex="m" country="us" level="2">Johannes Gehrke</researcher>
    <researcher sex="m" country="be" level="2">Bart Goethals</researcher>
    <researcher sex="m" country="us" level="2">Eamonn J. Keogh</researcher>
    <researcher sex="f" country="de" level="2">Kristian Kersting</researcher>
    <researcher sex="m" country="tw" level="2">Chih-Jen Lin</researcher>
    <researcher sex="m" country="us" level="2">Bing Liu</researcher>
    <researcher sex="m" country="us" level="2">Srinivasan Parthasarathy</researcher>
    <researcher sex="m" country="us" level="2">Mohammed Javeed Zaki</researcher>
    <researcher sex="m" country="us" level="1">Naoki Abe</researcher>
    <researcher sex="m" country="us" level="1">Rakesh Agrawal</researcher>
    <researcher sex="f" country="us" level="1">Kristin P. Bennett</researcher>
    <researcher sex="m" country="de" level="1">Michael R. Berthold</researcher>
    <researcher sex="m" country="fr" level="1">Jean-François Boulicaut</researcher>
    <researcher sex="f" country="us" level="1">Carla E. Brodley</researcher>
    <researcher sex="m" country="au" level="1">Wray L. Buntine</researcher>
    <researcher sex="m" country="nl" level="1">Toon Calders</researcher>
    <researcher sex="m" country="au" level="1">Sanjay Chawla</researcher>
    <researcher sex="m" country="us" level="1">William W. Cohen</researcher>
    <researcher sex="m" country="us" level="1">Mark Craven</researcher>
    <researcher sex="m" country="us" level="1">Ian Davidson</researcher>
    <researcher sex="m" country="us" level="1">Chris H. Q. Ding</researcher>
    <researcher sex="m" country="si" level="1">Saso Dzeroski</researcher>
    <researcher sex="m" country="uk" level="1">Peter A. Flach</researcher>
    <researcher sex="m" country="pt" level="1">João Gama</researcher>
    <researcher sex="m" country="us" level="1">Joydeep Ghosh</researcher>
    <researcher sex="m" country="uk" level="1">David J. Hand</researcher>
    <researcher sex="m" country="pl" level="1">Szymon Jaroszewicz</researcher>
    <researcher sex="m" country="us" level="1">Thorsten Joachims</researcher>
    <researcher sex="m" country="us" level="1">C. David Page Jr.</researcher>
    <researcher sex="m" country="us" level="1">Vipin Kumar</researcher>
    <researcher sex="m" country="us" level="1">Ravi Kumar</researcher>
    <researcher sex="m" country="us" level="1">Pat Langley</researcher>
    <researcher sex="f" country="si" level="1">Nada Lavrac</researcher>
    <researcher sex="m" country="us" level="1">Jure Leskovec</researcher>
    <researcher sex="m" country="us" level="1">Andrew McCallum</researcher>
    <researcher sex="m" country="us" level="1">Prem Melville</researcher>
    <researcher sex="f" country="de" level="1">Katharina Morik</researcher>
    <researcher sex="m" country="ca" level="1">Jian Pei</researcher>
    <researcher sex="m" country="us" level="1">Foster J. Provost</researcher>
    <researcher sex="m" country="be" level="1">Luc De Raedt</researcher>
    <researcher sex="m" country="us" level="1">Naren Ramakrishnan</researcher>
    <researcher sex="m" country="us" level="1">R. Bharat Rao</researcher>
    <researcher sex="m" country="de" level="1">Tobias Scheffer</researcher>
    <researcher sex="m" country="us" level="1">Jude W. Shavlik</researcher>
    <researcher sex="m" country="nl" level="1">Arno Siebes</researcher>
    <researcher sex="m" country="us" level="1">Padhraic Smyth</researcher>
    <researcher sex="m" country="au" level="1">Kai Ming Ting</researcher>
    <researcher sex="m" country="fi" level="1">Hannu Toivonen</researcher>
    <researcher sex="m" country="de" level="1">Volker Tresp</researcher>
    <researcher sex="m" country="us" level="1">Alexander Tuzhilin</researcher>
    <researcher sex="m" country="us" level="1">Ramasamy Uthurusamy</researcher>
    <researcher sex="m" country="us" level="1">Chris Volinsky</researcher>
    <researcher sex="m" country="jp" level="1">Takashi Washio</researcher>
    <researcher sex="m" country="us" level="1">Xindong Wu</researcher>
    <researcher sex="f" country="br" level="1">Bianca Zadrozny</researcher>
    <researcher sex="m" country="ca" level="1">Osmar R. Zaïane</researcher>
    <researcher sex="f" country="us" level="1">Wei Wang 0010</researcher>
  </journal>
  <journal>
    <titleISI>IEEE Pervas Comput</titleISI>
    <titleDBLP>IEEE Pervasive Computing</titleDBLP>
    <isbn>1536-1268</isbn>
    <publisher>IEEE</publisher>
    <if5years> 4.395</if5years>
    <researcher sex="m" country="uk" level="5">Nigel Davies</researcher>
    <researcher sex="m" country="us" level="4">Ramón Cáceres</researcher>
    <researcher sex="f" country="us" level="4">Maria Ebling</researcher>
    <researcher sex="m" country="de" level="4">Paul Lukowicz</researcher>
    <researcher sex="m" country="us" level="4">Chandrasekhar Narayanaswami</researcher>
    <researcher sex="m" country="us" level="4">Joseph A. Paradiso</researcher>
    <researcher sex="m" country="de" level="4">Albrecht Schmidt</researcher>
    <researcher sex="m" country="us" level="3">Mahadev Satyanarayanan</researcher>
    <researcher sex="m" country="us" level="3">Roy Want</researcher>
    <researcher sex="f" country="us" level="2">Mary Baker</researcher>
    <researcher sex="m" country="us" level="2">Tucker R. Balch</researcher>
    <researcher sex="m" country="us" level="2">John F. Canny</researcher>
    <researcher sex="m" country="us" level="2">Anind K. Dey</researcher>
    <researcher sex="f" country="us" level="2">Deborah Estrin</researcher>
    <researcher sex="m" country="us" level="2">Keith I. Farkas</researcher>
    <researcher sex="m" country="uk" level="2">Hans-Werner Gellersen</researcher>
    <researcher sex="m" country="us" level="2">Abdelsalam Helal</researcher>
    <researcher sex="m" country="us" level="2">Jason I. Hong</researcher>
    <researcher sex="m" country="us" level="2">Anthony D. Joseph</researcher>