=== slr3073/SOA-Curse/maar-2022-tp2-xml-slr3073a/src/main/resources/exo3/FilmProviderEbauche.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.example.com/films/v1"
           targetNamespace="http://www.example.com/films/v1" elementFormDefault="qualified">

    <xsd:element name="prenom"/>
    <xsd:element name="nom"/>
    <xsd:element name="realisateur">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="prenom"/>
                <xsd:element ref="nom"/>
            </xsd:sequence>
            <xsd:attribute name="id_realisateur" use="required"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="titre"/>
    <xsd:element name="text"/>
    <xsd:element name="resume">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="text"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="film">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="titre"/>
                <xsd:element ref="resume"/>
            </xsd:sequence>
            <xsd:attribute name="id_film" use="required"/>
            <xsd:attribute name="id_realisateur" use="required"/>
            <xsd:attribute name="annee" use="required"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="films">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="realisateur"/>
                <xsd:element ref="film"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== slr3073/SOA-Curse/maar-2022-tp2-xml-slr3073a/src/main/resources/exo3/FilmProviderEbauche.xml
<?xml version="1.0" encoding="UTF-8"?>
<films xmlns:xsdi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://www.example.com/films/v1"
    xsdi:schemaLocation="http://www.example.com/films/v1 FilmProviderEbauche.xsd">
    <realisateur id_realisateur="real_01">
        <prenom>Pedro</prenom>
        <nom>Almodovar</nom>
    </realisateur>
    <film id_film="film_01" id_realisateur="real_01" annee="2006">
        <titre>Volver</titre>
        <resume>
            <text>Une histoire transgénérationnelle</text>
        </resume>
    </film>
</films>
